services:
  api:
    build: .
    container_name: urlshortener_api
    restart: always
    ports:
      - "80:8000"
    environment:
      APP_ENV: production   
    env_file:
      - .env.prod

volumes: {}